export const rolePermissions = {
  admin: [
    'comptes',
    'articles',
    'ajouter-entree',
    'entrees-en-attente',
    'entrees-confirme',
    'ajouter-sortie',
    'sorties-en-attente',
    'sorties-confirme',
    'fournisseurs',
    'fabriquants',
    'classement',
    'chantiers',
    'demandes',
    'retours',
    'notifications',
    'configuration',
  ],
  admin1: [
    'articles',
    'ajouter-entree',
    'entrees-en-attente',
    'entrees-confirme',
    'ajouter-sortie',
    'sorties-en-attente',
    'sorties-confirme',
    'fournisseurs',
    'fabriquants',
    'classement',
    'chantiers',
    'demandes',
    'retours',
    'notifications',
    'configuration',
  ],
  admin2: [
    'articles',
    'fournisseurs',
    'fabriquants',
    'classement',
    'chantiers',
    'demandes',
    'retours',
    'notifications',
    'configuration',
  ],
  'responsable-chantier': ['demandes', 'retours'],
  magazinier: ['articles', 'ajouter-entree', 'ajouter-sortie'],
};
